blank_issues_enabled: false
contact_links:
<<<<<<< HEAD
  - name: Feature request? Questions regarding some extension?
    url: https://github.com/AbdBarho/stable-diffusion-webui-docker/discussions
    about: Please use the discussions tab
=======
  - name: WebUI Community Support
    url: https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions
    about: Please ask and answer questions here.
>>>>>>> feee37d75f1b168768014e4634dcb156ee649c05
